var optionList = {
    "u":{
        "name":"Up",
        "type":"quark",
        "charge":2/3,
        "lepton":0,
        "baryon":1/3,
        "strangeness":0,
        "mass":2.2
    },
    "d":{
        "name":"Down",
        "type":"quark",
        "charge":-1/3,
        "lepton":0,
        "baryon":1/3,
        "strangeness":"0",
        "mass":4.6
    },
    "c":{
        "name":"Charm",
        "type":"quark",
        "charge":2/3,
        "lepton":0,
        "baryon":1/3,
        "strangeness":0,
        "mass":1280
    },
    "s":{
        "name":"Strange",
        "type":"quark",
        "charge":-1/3,
        "lepton":0,
        "baryon":1/3,
        "strangeness":-1,
        "mass":96
    },
    "t":{
        "name":"Top",
        "type":"quark",
        "charge":2/3,
        "lepton":0,
        "baryon":1/3,
        "strangeness":0,
        "mass":173100
    },
    "b":{
        "name":"Bottom",
        "type":"quark",
        "charge":-1/3,
        "lepton":0,
        "baryon":1/3,
        "strangeness":0,
        "mass":4180
    },
    "e-":{
        "name":"Electron",
        "type":"lepton",
        "charge":-1,
        "lepton":1,
        "baryon":0,
        "strangeness":0,
        "mass":0.511
    },
    "ve-":{
        "name":"Electron neutrino",
        "type":"lepton",
        "charge":0,
        "lepton":1,
        "baryon":0,
        "strangeness":0,
        "mass":0.0000022
    },
    "mu":{
        "name":"Muon",
        "type":"lepton",
        "charge":-1,
        "lepton":1,
        "baryon":0,
        "strangeness":0,
        "mass":105.66
    },
    "vmu":{
        "name":"Muon neutrino",
        "type":"lepton",
        "charge":0,
        "lepton":1,
        "baryon":0,
        "strangeness":0,
        "mass":0.17
    },
    "tau":{
        "name":"Tau",
        "type":"lepton",
        "charge":-1,
        "lepton":1,
        "baryon":0,
        "strangeness":0,
        "mass":1776.8
    },
    "vtau":{
        "name":"Tau neutrino",
        "type":"lepton",
        "charge":0,
        "lepton":1,
        "baryon":0,
        "strangeness":0,
        "mass":18.2
    },
    "-u":{
        "name":"Anti-Up",
        "type":"quark",
        "charge":-2/3,
        "lepton":0,
        "baryon":-1/3,
        "strangeness":0,
        "mass":2.2
    },
    "-d":{
        "name":"Anti-Down",
        "type":"quark",
        "charge":1/3,
        "lepton":0,
        "baryon":-1/3,
        "strangeness":0,
        "mass":4.6
    },
    "-c":{
        "name":"Anti-Charm",
        "type":"quark",
        "charge":-2/3,
        "lepton":0,
        "baryon":-1/3,
        "strangeness":0,
        "mass":1280
    },
    "-s":{
        "name":"Anti-Strange",
        "type":"quark",
        "charge":1/3,
        "lepton":0,
        "baryon":-1/3,
        "strangeness":1,
        "mass":96
    },
    "-t":{
        "name":"Anti-Top",
        "type":"quark",
        "charge":-2/3,
        "lepton":0,
        "baryon":-1/3,
        "strangeness":0,
        "mass":173100
    },
    "-b":{
        "name":"Anti-Bottom",
        "type":"quark",
        "charge":1/3,
        "lepton":0,
        "baryon":-1/3,
        "strangeness":0,
        "mass":4180
    },
    "e+":{
        "name":"Anti-Electron",
        "type":"lepton",
        "charge":1,
        "lepton":-1,
        "baryon":0,
        "strangeness":0,
        "mass":0.511
    },
    "ve+":{
        "name":"Electron Anti-neutrino",
        "type":"lepton",
        "charge":0,
        "lepton":-1,
        "baryon":0,
        "strangeness":0,
        "mass":0.0000022
    },
    "-mu":{
        "name":"Anti-Muon",
        "type":"lepton",
        "charge":1,
        "lepton":-1,
        "baryon":0,
        "strangeness":0,
        "mass":105.66
    },
    "-vmu":{
        "name":"Anti-Muon neutrino",
        "type":"lepton",
        "charge":0,
        "lepton":-1,
        "baryon":0,
        "strangeness":0,
        "mass":0.17
    },
    "-tau":{
        "name":"Anti-Tau",
        "type":"lepton",
        "charge":1,
        "lepton":-1,
        "baryon":0,
        "strangeness":0,
        "mass":1776.8
    },
    "-vtau":{
        "name":"Anti-Tau neutrino",
        "type":"lepton",
        "charge":0,
        "lepton":-1,
        "baryon":0,
        "strangeness":0,
        "mass":18.2
    },
    "p":{
        "name":"Proton",
        "type":"baryon",
        "charge":1,
        "lepton":0,
        "baryon":0,
        "strangeness":0,
        "mass":938.28
    },
    "n":{
        "name":"Neutron",
        "type":"baryon",
        "charge":0,
        "lepton":0,
        "baryon":0,
        "strangeness":0,
        "mass":939.57
    },
    "-p":{
        "name":"Anti-Proton",
        "type":"baryon",
        "charge":-1,
        "lepton":0,
        "baryon":0,
        "strangeness":0,
        "mass":938.28
    },
    "-n":{
        "name":"Anti-Neutron",
        "type":"baryon",
        "charge":0,
        "lepton":0,
        "baryon":0,
        "strangeness":0,
        "mass":939.57
    },
    "pi+":{
        "name":"Pion+",
        "type":"meson",
        "charge":1,
        "lepton":0,
        "baryon":0,
        "strangeness":0,
        "mass":139.6
    },
    "pi-":{
        "name":"Pion-",
        "type":"meson",
        "charge":-1,
        "lepton":0,
        "baryon":0,
        "strangeness":0,
        "mass":139.6
    },
    "pi0":{
        "name":"Pion0",
        "type":"meson",
        "charge":0,
        "lepton":0,
        "baryon":0,
        "strangeness":0,
        "mass":135.0
    },
    "k+":{
        "name":"Kaon+",
        "type":"meson",
        "charge":1,
        "lepton":0,
        "baryon":0,
        "strangeness":0,
        "mass":493.677
    },
    "k-":{
        "name":"Kaon-",
        "type":"meson",
        "charge":-1,
        "lepton":0,
        "baryon":0,
        "strangeness":0,
        "mass":493.677
    },
    "k0":{
        "name":"Kaon0",
        "type":"meson",
        "charge":0,
        "lepton":0,
        "baryon":0,
        "strangeness":0,
        "mass":497.648
    }
}